runner: !DetectionRunner
  rdt_enabled: True
  node: !KubernetesNode
    ssl: !SSL
      server_verify: False
      client_key_path: "CRT_PATH/apiserver-kubelet-client.key"
      client_cert_path: "CRT_PATH/apiserver-kubelet-client.crt"
    kubelet_endpoint: "https://100.64.176.17:10250"
    monitored_namespaces: ["default"]
  action_delay: 10.
  metrics_storage: !KafkaStorage
    brokers_ips: ['100.64.176.12:9092']
    topic: "wca_metrics"
    max_timeout_in_seconds: 5.
  anomalies_storage: !KafkaStorage
    brokers_ips: ['100.64.176.12:9092']
    topic: "wca_anomalies"
    max_timeout_in_seconds: 5.
  detector: !ContentionDetector
    database: !ModelDatabase
      db_type: local
      host: ~
      directory: WORKSPACE/BUILD_NUMBER
    action_delay: 10.

  extra_labels:
    env_uniq_id: "17"
    own_ip: "100.64.176.17"
    build_commit: "BUILD_COMMIT"
    build_number: "BUILD_NUMBER"
    build_scenario: "BUILD_SCENARIO"
